#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Mar 16 20:43:38 IST 2026
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_4x4_behav -key {Behavioral:sim_1:Functional:tb_4x4} -tclbatch tb_4x4.tcl -view /home/avinash/static_config_final/tb_2x2_behav.wcfg -view /home/avinash/static_config_final/tb_4x4_behav.wcfg -log simulate.log"
xsim tb_4x4_behav -key {Behavioral:sim_1:Functional:tb_4x4} -tclbatch tb_4x4.tcl -view /home/avinash/static_config_final/tb_2x2_behav.wcfg -view /home/avinash/static_config_final/tb_4x4_behav.wcfg -log simulate.log

